version: "3.4"

services:
  backend_mariadb:
    image: db-mariadb-prod:1.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: ms*1241
    restart: on-failure
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
    # persist data (inside docker)
      - datacontainer:/var/lib/mysql
      - ./patch/health-check.sh:/usr/local/bin/health-check.sh
    ports:
      - "3306:3306"
#    healthcheck:
#      test: ["CMD", "/usr/local/bin/health-check.sh"]
#      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
volumes:
  # persist data (inside docker)
  datacontainer: