version: "3.4"

services:
  backend_mariadb:
    image: db-mariadb-prod:1.0.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: ms*1241
    restart: on-failure
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
# persist data
      - datacontainer:/var/lib/mysql
    ports:
      - "3306:3306"
#    healthcheck:
#      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 30s
volumes:
  datacontainer: