version: "3.4"

services:
  nginx:
    build:
      context: deploy/docker/nginx
      dockerfile: Dockerfile
      target: app_nginx
      args:
        - IMAGE_NAME=nginx
        - IMAGE_TAG=1.20-alpine
        - CONTENT_FOLDER=/usr/share/nginx
        - ASSETS_FOLDER=/usr/share/nginx
        - HTML_FOLDER=/usr/share/nginx
    volumes:
      - ./public:/usr/share/nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  php:
    build:
      context: deploy/docker/php
      dockerfile: Dockerfile
      target: php-production-stage
      args:
        - PHP_VERSION=8.1.12
        - ALPINE_VERSION=3.16
        - SERVICE_NAME=php
        - EXPOSE_PORT=9000
        - YAML_VERSION=2.2.2
        - REDIS_VERSION=5.3.7
    volumes:
      - ./api/001/src:/var/www/html
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_APP_USER}
      - DATABASE_PWD=${DATABASE_APP_PASSWORD}
    ports:
      - "9000:80"

  db:
    build:
      context: deploy/docker/mariadb
      dockerfile: Dockerfile
      target: app_db
      args:
        - IMAGE_NAME=mariadb
        - IMAGE_TAG=10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_APP_USER}
      - MYSQL_PASSWORD=${DATABASE_APP_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
#
#  phpmyadmin:
#    build:
#      context: deploy/docker/phpmyadmin
#      dockerfile: Dockerfile
#      target: app_php_myadmin
#      args:
#        - IMAGE_NAME=phpmyadmin/phpmyadmin
#        - IMAGE_TAG=latest
#    ports:
#      - "8080:80"
#    environment:
#      - PMA_HOST=${DATABASE_HOST}
#    depends_on:
#      - db

volumes:
  mysqldata: