version: "3.4"

services:
  nginx:
    build:
      context: deploy/docker
      dockerfile: Dockerfile.Nginx
      target: app_nginx
      args:
      - IMAGE_NAME=nginx
      - IMAGE_TAG=1.20-alpine
    volumes:
      - ./public:/usr/share/nginx
      - ./deploy/base/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/base/nginx/locations/:/etc/nginx/locations
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  php:
    build:
      context: deploy/docker
      dockerfile: Dockerfile.PHP
      target: app_php
      args:
        - WORK_DIR=${PHP_WORK_DIR}
        - IMAGE_NAME=${PHP_IMAGE_NAME}
        - IMAGE_TAG=${PHP_IMAGE_TAG}
        - COMPOSER_TAG=${PHP_COMPOSER_TAG}
#
        - APK_TMP_ADD=${PHP_APK_TMP_ADD}
        - APK_ADD=${PHP_APK_ADD}
        - EXT_CONFIG=${PHP_EXT_CONFIG}
        - EXT_INSTALL=${PHP_EXT_INSTALL}
        - PLUGIN_MYSQL=${PHP_PLUGIN_MYSQL}
        - PLUGIN_YAML_VERSION=${PHP_PLUGIN_YAML_VERSION}
        - PLUGIN_REDIS_VERSION=${PHP_PLUGIN_REDIS_VERSION}
    volumes:
      - ./api/001/src:/var/www/html
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_APP_USER}
      - DATABASE_PWD=${DATABASE_APP_PASSWORD}
    ports:
      - "9000:80"

  db:
    build:
      context: deploy/docker
      dockerfile: Dockerfile.MariaDB
      target: app_db
      args:
        - IMAGE_NAME=mariadb
        - IMAGE_TAG=10.9.3
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_APP_USER}
      - MYSQL_PASSWORD=${DATABASE_APP_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    build:
      context: deploy/docker
      dockerfile: Dockerfile.PHPMyAdmin
      target: app_php_myadmin
      args:
        - IMAGE_NAME=phpmyadmin/phpmyadmin
        - IMAGE_TAG=latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${DATABASE_HOST}
    depends_on:
      - db

volumes:
  mysqldata: