
ARG IMAGE_NAME
ARG IMAGE_TAG

FROM ${IMAGE_NAME}:${IMAGE_TAG} as app_nginx

#
# add certbot
#
# RUN apk add certbot
# certbot certonly --webroot -w /usr/share/nginx -d www.noframework.io --email it@noframework.io --non-interactive --agree-tos
